apiVersion: v1
kind: Service
metadata:
  name: jenkins-ext-ip
spec:
  selector:
    mypod: my-jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080
  externalIPs:
    - 172.31.8.127
