apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-replicaset
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      mypod: my-jenkins
  template:
    metadata:
      labels:
        mypod: my-jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
