apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploymentset
  labels:
    app: jenkins-set
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins-set
  template:
    metadata:
      labels:
        app: jenkins-set
    spec:
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-volume
        ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 0
        fsGroup: 0
     
