---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    mypod: my-tomcat
spec:
  containers:
    - name: jenkins
      image: tomcat:latest


---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-loadbalancer
spec:
  type: LoadBalancer
  selector:
    mypod: my-tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
